const CEDEARS = [
  // === TECHNOLOGY ===
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology", ratio: 20 },
  { ticker: "MSFT", name: "Microsoft Corp.", sector: "Technology", ratio: 30 },
  { ticker: "GOOGL", name: "Alphabet Inc.", sector: "Technology", ratio: 58 },
  { ticker: "NVDA", name: "NVIDIA Corp.", sector: "Technology", ratio: 24 },
  { ticker: "META", name: "Meta Platforms", sector: "Technology", ratio: 24 },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Technology", ratio: 10 },
  { ticker: "INTC", name: "Intel Corp.", sector: "Technology", ratio: 5 },
  { ticker: "CRM", name: "Salesforce Inc.", sector: "Technology", ratio: 18 },
  { ticker: "ORCL", name: "Oracle Corp.", sector: "Technology", ratio: 3 },
  { ticker: "ADBE", name: "Adobe Inc.", sector: "Technology", ratio: 44 },
  { ticker: "GLOB", name: "Globant S.A.", sector: "Technology", ratio: 18 },
  { ticker: "SHOP", name: "Shopify Inc.", sector: "Technology", ratio: 107 },
  { ticker: "TSM", name: "Taiwan Semiconductor", sector: "Technology", ratio: 9 },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology", ratio: 39 },
  { ticker: "CSCO", name: "Cisco Systems", sector: "Technology", ratio: 5 },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology", ratio: 5 },
  { ticker: "QCOM", name: "Qualcomm Inc.", sector: "Technology", ratio: 11 },
  { ticker: "AMAT", name: "Applied Materials", sector: "Technology", ratio: 5 },
  { ticker: "MU", name: "Micron Technology", sector: "Technology", ratio: 5 },
  { ticker: "MRVL", name: "Marvell Technology", sector: "Technology", ratio: 14 },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology", ratio: 50 },
  { ticker: "NOW", name: "ServiceNow Inc.", sector: "Technology", ratio: 172 },
  { ticker: "PLTR", name: "Palantir Technologies", sector: "Technology", ratio: 3 },
  { ticker: "SAP", name: "SAP SE", sector: "Technology", ratio: 6 },
  { ticker: "IBM", name: "IBM Corp.", sector: "Technology", ratio: 15 },
  { ticker: "ASML", name: "ASML Holding", sector: "Technology", ratio: 146 },
  { ticker: "TEAM", name: "Atlassian Corp.", sector: "Technology", ratio: 47 },
  { ticker: "ARM", name: "ARM Holdings", sector: "Technology", ratio: 27 },
  { ticker: "LRCX", name: "Lam Research", sector: "Technology", ratio: 56 },
  { ticker: "SNOW", name: "Snowflake Inc.", sector: "Technology", ratio: 30 },
  { ticker: "AI", name: "C3.ai Inc.", sector: "Technology", ratio: 5 },
  { ticker: "MSTR", name: "MicroStrategy", sector: "Technology", ratio: 20 },

  // === CONSUMER CYCLICAL ===
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Cyclical", ratio: 144 },
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer Cyclical", ratio: 15 },
  { ticker: "MELI", name: "MercadoLibre Inc.", sector: "Consumer Cyclical", ratio: 120 },
  { ticker: "NKE", name: "Nike Inc.", sector: "Consumer Cyclical", ratio: 12 },
  { ticker: "SBUX", name: "Starbucks Corp.", sector: "Consumer Cyclical", ratio: 12 },
  { ticker: "HD", name: "Home Depot Inc.", sector: "Consumer Cyclical", ratio: 32 },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer Cyclical", ratio: 700 },
  { ticker: "TGT", name: "Target Corp.", sector: "Consumer Cyclical", ratio: 24 },
  { ticker: "ABNB", name: "Airbnb Inc.", sector: "Consumer Cyclical", ratio: 15 },
  { ticker: "DECK", name: "Deckers Outdoor", sector: "Consumer Cyclical", ratio: 25 },
  { ticker: "ETSY", name: "Etsy Inc.", sector: "Consumer Cyclical", ratio: 16 },
  { ticker: "GM", name: "General Motors", sector: "Consumer Cyclical", ratio: 6 },
  { ticker: "F", name: "Ford Motor Co.", sector: "Consumer Cyclical", ratio: 1 },
  { ticker: "NIO", name: "NIO Inc.", sector: "Consumer Cyclical", ratio: 4 },
  { ticker: "XPEV", name: "XPeng Inc.", sector: "Consumer Cyclical", ratio: 4 },
  { ticker: "RACE", name: "Ferrari N.V.", sector: "Consumer Cyclical", ratio: 83 },
  { ticker: "TJX", name: "TJX Companies", sector: "Consumer Cyclical", ratio: 22 },

  // === ALIMENTOS & CONSUMER DEFENSIVE ===
  { ticker: "KO", name: "Coca-Cola Co.", sector: "Consumer Defensive", ratio: 5 },
  { ticker: "PEP", name: "PepsiCo Inc.", sector: "Consumer Defensive", ratio: 18 },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer Defensive", ratio: 18 },
  { ticker: "COST", name: "Costco Wholesale", sector: "Consumer Defensive", ratio: 48 },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer Defensive", ratio: 15 },
  { ticker: "MCD", name: "McDonald's Corp.", sector: "Consumer Defensive", ratio: 24 },
  { ticker: "MDLZ", name: "Mondelez International", sector: "Consumer Defensive", ratio: 15 },
  { ticker: "HSY", name: "The Hershey Co.", sector: "Consumer Defensive", ratio: 21 },
  { ticker: "KMB", name: "Kimberly-Clark", sector: "Consumer Defensive", ratio: 6 },
  { ticker: "CL", name: "Colgate-Palmolive", sector: "Consumer Defensive", ratio: 3 },
  { ticker: "UL", name: "Unilever PLC", sector: "Consumer Defensive", ratio: 3 },
  { ticker: "PM", name: "Philip Morris Intl", sector: "Consumer Defensive", ratio: 18 },
  { ticker: "MO", name: "Altria Group", sector: "Consumer Defensive", ratio: 4 },
  { ticker: "DEO", name: "Diageo PLC", sector: "Consumer Defensive", ratio: 6 },
  { ticker: "SYY", name: "Sysco Corp.", sector: "Consumer Defensive", ratio: 8 },
  { ticker: "FMX", name: "FEMSA", sector: "Consumer Defensive", ratio: 6 },
  { ticker: "KOFM", name: "Coca-Cola FEMSA", sector: "Consumer Defensive", ratio: 2 },
  { ticker: "BNG", name: "Bunge Limited", sector: "Consumer Defensive", ratio: 5 },
  { ticker: "MOS", name: "The Mosaic Co.", sector: "Consumer Defensive", ratio: 5 },
  { ticker: "ABEV", name: "Ambev S.A.", sector: "Consumer Defensive", ratio: 0.33 },

  // === FINANCIAL ===
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Financial", ratio: 15 },
  { ticker: "V", name: "Visa Inc.", sector: "Financial", ratio: 18 },
  { ticker: "MA", name: "Mastercard Inc.", sector: "Financial", ratio: 33 },
  { ticker: "GS", name: "Goldman Sachs", sector: "Financial", ratio: 13 },
  { ticker: "BA.C", name: "Bank of America", sector: "Financial", ratio: 4 },
  { ticker: "BRKB", name: "Berkshire Hathaway B", sector: "Financial", ratio: 22 },
  { ticker: "C", name: "Citigroup Inc.", sector: "Financial", ratio: 3 },
  { ticker: "WFC", name: "Wells Fargo", sector: "Financial", ratio: 5 },
  { ticker: "AXP", name: "American Express", sector: "Financial", ratio: 15 },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Financial", ratio: 13 },
  { ticker: "BK", name: "Bank of NY Mellon", sector: "Financial", ratio: 2 },
  { ticker: "PYPL", name: "PayPal Holdings", sector: "Financial", ratio: 8 },
  { ticker: "XYZ", name: "Block Inc. (Square)", sector: "Financial", ratio: 20 },
  { ticker: "COIN", name: "Coinbase Global", sector: "Financial", ratio: 27 },
  { ticker: "UN", name: "Nu Holdings", sector: "Financial", ratio: 2 },
  { ticker: "SPGI", name: "S&P Global Inc.", sector: "Financial", ratio: 45 },
  { ticker: "HSBC", name: "HSBC Holdings", sector: "Financial", ratio: 2 },

  // === HEALTHCARE & PHARMA ===
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", ratio: 15 },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Healthcare", ratio: 4 },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Healthcare", ratio: 10 },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare", ratio: 33 },
  { ticker: "MRK", name: "Merck & Co.", sector: "Healthcare", ratio: 5 },
  { ticker: "LLY", name: "Eli Lilly & Co.", sector: "Healthcare", ratio: 56 },
  { ticker: "MRNA", name: "Moderna Inc.", sector: "Healthcare", ratio: 19 },
  { ticker: "BMY", name: "Bristol-Myers Squibb", sector: "Healthcare", ratio: 3 },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare", ratio: 4 },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Healthcare", ratio: 30 },
  { ticker: "TMO", name: "Thermo Fisher Scientific", sector: "Healthcare", ratio: 22 },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare", ratio: 90 },
  { ticker: "MDT", name: "Medtronic PLC", sector: "Healthcare", ratio: 4 },
  { ticker: "AZN", name: "AstraZeneca PLC", sector: "Healthcare", ratio: 2 },
  { ticker: "NVS", name: "Novartis AG", sector: "Healthcare", ratio: 4 },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals", sector: "Healthcare", ratio: 101 },
  { ticker: "BIIB", name: "Biogen Inc.", sector: "Healthcare", ratio: 13 },
  { ticker: "GSK", name: "GSK PLC", sector: "Healthcare", ratio: 4 },

  // === ENERGY ===
  { ticker: "XOM", name: "Exxon Mobil Corp.", sector: "Energy", ratio: 10 },
  { ticker: "CVX", name: "Chevron Corp.", sector: "Energy", ratio: 16 },
  { ticker: "SHEL", name: "Shell PLC", sector: "Energy", ratio: 2 },
  { ticker: "BP", name: "BP PLC", sector: "Energy", ratio: 5 },
  { ticker: "TTE", name: "TotalEnergies SE", sector: "Energy", ratio: 3 },
  { ticker: "SLB", name: "Schlumberger Ltd", sector: "Energy", ratio: 3 },
  { ticker: "HAL", name: "Halliburton Co.", sector: "Energy", ratio: 2 },
  { ticker: "OXY", name: "Occidental Petroleum", sector: "Energy", ratio: 5 },
  { ticker: "EQNR", name: "Equinor ASA", sector: "Energy", ratio: 6 },
  { ticker: "E", name: "Eni SpA", sector: "Energy", ratio: 4 },
  { ticker: "PSX", name: "Phillips 66", sector: "Energy", ratio: 6 },
  { ticker: "BKR", name: "Baker Hughes", sector: "Energy", ratio: 7 },
  { ticker: "VIST", name: "Vista Energy (Argentina)", sector: "Energy", ratio: 3 },
  { ticker: "PBR", name: "Petrobras", sector: "Energy", ratio: 1 },
  { ticker: "CEG", name: "Constellation Energy", sector: "Energy", ratio: 45 },
  { ticker: "VST", name: "Vistra Corp.", sector: "Energy", ratio: 26 },

  // === COMMUNICATION ===
  { ticker: "NFLX", name: "Netflix Inc.", sector: "Communication", ratio: 48 },
  { ticker: "DISN", name: "Walt Disney Co.", sector: "Communication", ratio: 12 },
  { ticker: "SPOT", name: "Spotify Technology", sector: "Communication", ratio: 28 },
  { ticker: "T", name: "AT&T Inc.", sector: "Communication", ratio: 3 },
  { ticker: "VZ", name: "Verizon Communications", sector: "Communication", ratio: 4 },
  { ticker: "TMUS", name: "T-Mobile US", sector: "Communication", ratio: 33 },
  { ticker: "BIDU", name: "Baidu Inc.", sector: "Communication", ratio: 11 },
  { ticker: "SNAP", name: "Snap Inc.", sector: "Communication", ratio: 1 },
  { ticker: "PINS", name: "Pinterest Inc.", sector: "Communication", ratio: 7 },
  { ticker: "EA", name: "Electronic Arts", sector: "Communication", ratio: 14 },
  { ticker: "RBLX", name: "Roblox Corp.", sector: "Communication", ratio: 2 },

  // === INDUSTRIALS ===
  { ticker: "BA", name: "Boeing Co.", sector: "Industrials", ratio: 24 },
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrials", ratio: 20 },
  { ticker: "DE", name: "Deere & Company", sector: "Industrials", ratio: 40 },
  { ticker: "UBER", name: "Uber Technologies", sector: "Industrials", ratio: 2 },
  { ticker: "HON", name: "Honeywell Intl", sector: "Industrials", ratio: 8 },
  { ticker: "UNP", name: "Union Pacific", sector: "Industrials", ratio: 20 },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrials", ratio: 20 },
  { ticker: "RTX", name: "Raytheon Technologies", sector: "Industrials", ratio: 5 },
  { ticker: "GE", name: "General Electric", sector: "Industrials", ratio: 8 },
  { ticker: "FDX", name: "FedEx Corp.", sector: "Industrials", ratio: 10 },
  { ticker: "MMM", name: "3M Company", sector: "Industrials", ratio: 10 },
  { ticker: "ERJ", name: "Embraer S.A.", sector: "Industrials", ratio: 1 },
  { ticker: "CAAP", name: "Corp. América Airports", sector: "Industrials", ratio: 0.25 },

  // === MATERIALS & MINING ===
  { ticker: "VALE", name: "Vale S.A.", sector: "Materials", ratio: 2 },
  { ticker: "FCX", name: "Freeport-McMoRan", sector: "Materials", ratio: 3 },
  { ticker: "NEM", name: "Newmont Corp.", sector: "Materials", ratio: 3 },
  { ticker: "AEM", name: "Agnico Eagle Mines", sector: "Materials", ratio: 6 },
  { ticker: "PAAS", name: "Pan American Silver", sector: "Materials", ratio: 3 },
  { ticker: "GFI", name: "Gold Fields Ltd", sector: "Materials", ratio: 1 },
  { ticker: "KGC", name: "Kinross Gold", sector: "Materials", ratio: 1 },
  { ticker: "HL", name: "Hecla Mining", sector: "Materials", ratio: 1 },
  { ticker: "HMY", name: "Harmony Gold Mining", sector: "Materials", ratio: 1 },
  { ticker: "RIO", name: "Rio Tinto PLC", sector: "Materials", ratio: 8 },
  { ticker: "BHP", name: "BHP Group Ltd", sector: "Materials", ratio: 2 },
  { ticker: "SCCO", name: "Southern Copper", sector: "Materials", ratio: 2 },
  { ticker: "NUE", name: "Nucor Corp.", sector: "Materials", ratio: 16 },
  { ticker: "DOW", name: "Dow Inc.", sector: "Materials", ratio: 6 },
  { ticker: "DD", name: "DuPont de Nemours", sector: "Materials", ratio: 5 },
  { ticker: "SID", name: "CSN Siderúrgica", sector: "Materials", ratio: 0.125 },
  { ticker: "GGB", name: "Gerdau S.A.", sector: "Materials", ratio: 0.25 },
  { ticker: "TXR", name: "Ternium S.A.", sector: "Materials", ratio: 4 },
  { ticker: "TEN", name: "Tenaris S.A.", sector: "Materials", ratio: 1 },

  // === E-COMMERCE ===
  { ticker: "BABA", name: "Alibaba Group", sector: "E-Commerce", ratio: 9 },
  { ticker: "JD", name: "JD.com Inc.", sector: "E-Commerce", ratio: 4 },
  { ticker: "SE", name: "Sea Limited", sector: "E-Commerce", ratio: 32 },
  { ticker: "PDD", name: "PDD Holdings (Temu)", sector: "E-Commerce", ratio: 25 },

  // === CRYPTO & BLOCKCHAIN ===
  { ticker: "RIOT", name: "Riot Platforms", sector: "Crypto", ratio: 3 },
  { ticker: "BITF", name: "Bitfarms Ltd", sector: "Crypto", ratio: 0.2 },
  { ticker: "HUT", name: "Hut 8 Mining", sector: "Crypto", ratio: 0.2 },

  // === ETFs (DIVERSIFICACIÓN) ===
  { ticker: "SPY", name: "SPDR S&P 500 ETF", sector: "ETF - Índices", ratio: 20 },
  { ticker: "QQQ", name: "Invesco QQQ (Nasdaq 100)", sector: "ETF - Índices", ratio: 20 },
  { ticker: "DIA", name: "SPDR Dow Jones", sector: "ETF - Índices", ratio: 20 },
  { ticker: "IWM", name: "iShares Russell 2000", sector: "ETF - Índices", ratio: 10 },
  { ticker: "EEM", name: "iShares MSCI Emerging", sector: "ETF - Internacional", ratio: 5 },
  { ticker: "EWZ", name: "iShares MSCI Brazil", sector: "ETF - Internacional", ratio: 2 },
  { ticker: "EFA", name: "iShares MSCI EAFE", sector: "ETF - Internacional", ratio: 18 },
  { ticker: "ACWI", name: "iShares MSCI ACWI", sector: "ETF - Internacional", ratio: 26 },
  { ticker: "XLE", name: "Energy Select SPDR", sector: "ETF - Sectorial", ratio: 2 },
  { ticker: "XLF", name: "Financial Select SPDR", sector: "ETF - Sectorial", ratio: 2 },
  { ticker: "XLK", name: "Technology Select SPDR", sector: "ETF - Sectorial", ratio: 46 },
  { ticker: "XLV", name: "Health Care Select SPDR", sector: "ETF - Sectorial", ratio: 29 },
  { ticker: "XLP", name: "Consumer Staples SPDR", sector: "ETF - Sectorial", ratio: 16 },
  { ticker: "XLI", name: "Industrial Select SPDR", sector: "ETF - Sectorial", ratio: 28 },
  { ticker: "XLB", name: "Materials Select SPDR", sector: "ETF - Sectorial", ratio: 18 },
  { ticker: "XLRE", name: "Real Estate Select SPDR", sector: "ETF - Sectorial", ratio: 9 },
  { ticker: "XLU", name: "Utilities Select SPDR", sector: "ETF - Sectorial", ratio: 15 },
  { ticker: "XLC", name: "Communication SPDR", sector: "ETF - Sectorial", ratio: 19 },
  { ticker: "XLY", name: "Consumer Discretionary SPDR", sector: "ETF - Sectorial", ratio: 43 },
  { ticker: "GLD", name: "SPDR Gold Trust", sector: "ETF - Commodities", ratio: 50 },
  { ticker: "SLV", name: "iShares Silver Trust", sector: "ETF - Commodities", ratio: 6 },
  { ticker: "USO", name: "United States Oil Fund", sector: "ETF - Commodities", ratio: 15 },
  { ticker: "GDX", name: "VanEck Gold Miners ETF", sector: "ETF - Commodities", ratio: 10 },
  { ticker: "URA", name: "Global X Uranium ETF", sector: "ETF - Commodities", ratio: 5 },
  { ticker: "SMH", name: "VanEck Semiconductor ETF", sector: "ETF - Sectorial", ratio: 50 },
  { ticker: "ARKK", name: "ARK Innovation ETF", sector: "ETF - Temático", ratio: 10 },
  { ticker: "IBIT", name: "iShares Bitcoin Trust", sector: "ETF - Crypto", ratio: 10 },
  { ticker: "ETHA", name: "iShares Ethereum Trust", sector: "ETF - Crypto", ratio: 5 },
  { ticker: "IBB", name: "iShares Nasdaq Biotech", sector: "ETF - Sectorial", ratio: 27 },
  { ticker: "ITA", name: "iShares US Aerospace", sector: "ETF - Sectorial", ratio: 50 },
  { ticker: "VIG", name: "Vanguard Dividend Appreciation", sector: "ETF - Dividendos", ratio: 39 },
];

export default CEDEARS;
